### ISSUE TITLE
User Error

### ISSUE THREAD

**Issue by nabheet** [andgineer/redis-redirect#7]
Found the problem. SORRY! my bad!

**Comment by andgineer** [comment]
in fact there WAS an error.
I forgot the __init__.py inside the package and the pip just did not copy the package at all.

fixed in version 0.1.8

**Comment by nabheet** [comment]
Oh! yeah I see it now. Today was a hectic day so I confused myself with everything that was happening.

Thank you for fixing it so quickly!
